### ISSUE TITLE
Is domain specific config available?

### ISSUE THREAD

**Issue by criation** [nuxt-modules/robots#111]
I do have two domains, lets say

staging.example.com
exmaple.com

now i want to have specific robots setting for each domain. It'd be nice to realize this by config like this:

```js
modules: [
    [...],
    ['@nuxtjs/robots', {
      UserAgent: '*',
      Disallow: '/admin',
      domains: {
        'exmaple.com': [
          { UserAgent: '*' },
          { Disallow: '/dashboard/' },
        ],
        'staging.example.com': [
          { UserAgent: '*' },
          { Disallow: '/' }, 
        ]
      }
    }],
  ],
```

is something like this already available?

**Comment by kenechukwuJosiah** [comment]
Currently, this module does not support configuration per domain, but you can dynamically generate your robot.txt based on the domain.

**Comment by quroom** [comment]
@criation Did you solve your problem?
Maybe you can acheive what you want with env.
```

  robots:
    process.env.STAGE === "production"
      ? {
          rules: [
            {
              UserAgent: "*",
              Allow: "/",
              Disallow: "/admin",
            },
          ],
        }
      : {
          rules: {
            UserAgent: "*",
            Disallow: "/",
          },
        },
```

I just set STAGE but you can set whatever you want as variable in env file.
And make your code works conditionally based on domians.
