### ISSUE TITLE
Robots.txt output is not what I write in nuxt.config.js

### ISSUE THREAD

**Issue by elisabetperez** [nuxt-modules/robots#118]
Hello, I'm using @nuxtjs/robots version 3.0.0 and whatever I write inside the options of the module is not being displayed in my robots.txt.

This is my module inside nuxt.config.js:
```
modules: [
    '@nuxtjs/supabase',
    '@nuxtjs/sanity',
    ['@nuxtjs/robots', {
      UserAgent: '*',
      Disallow: '',
      BlankLine: true ,
      Comment: 'Comment here',
    }]
  ],
```

and my output is simply:
```
User-agent: *
Disallow: 
```

Could you help me find it why? Thanks

**Comment by kreativwolke** [comment]
Hello :-) Your configuration is not correct.

It should look like this.

`
modules: [
	'@nuxtjs/supabase',
	'@nuxtjs/sanity',
	['@nuxtjs/robots', {
	rules: [
		{ UserAgent: '*' },
		{ Disallow: '' },
		{ BlankLine: true },
		{ Comment: 'Comment here' },
	  ]
	}]
  ],`

I hope this was helpful.

**Comment by eric-scott-owens** [comment]
@kreativwolke, this might be worth including your code in the sample on the readme. It's definitely documented. But, I ended up here trying to figure it out as well.

**Comment by Hoan-Duong** [comment]
same here !

**Comment by Hoan-Duong** [comment]
> Hello :-) Your configuration is not correct.
> 
> It should look like this.
> 
> `modules: [ '@nuxtjs/supabase', '@nuxtjs/sanity', ['@nuxtjs/robots', { rules: [ { UserAgent: '*' }, { Disallow: '' }, { BlankLine: true }, { Comment: 'Comment here' }, ] }] ],`
> 
> I hope this was helpful.

Thanks, I followed and robots.txt worked!!

**Comment by bolddkdev** [comment]
Hello Guys,

I'm actually facing the same problem, is it being resolved?
  
  Output: 
  User-agent: *
  Disallow: 

`modules: [
    "@pinia/nuxt",
    "@vesp/nuxt-fontawesome",
    "@ambitiondev/nuxt-cookiebot",
    "nuxt-swiper",
    [
      "@nuxtjs/robots",
      {
        UserAgent: "*",
        Disallow: "/",
      },
    ],
  ],`

**Comment by andrzejkupczyk** [comment]
@kreativwolke already provided a solution 🤷🏻 Each rule must be added as a separate array entry (Rule).

There's also an example in the docs https://nuxt.com/modules/robots#robots-config

In your case, @bolddkdev , it should be:

```js
modules: [
    // ...
    ["@nuxtjs/robots", {
        rules: [
            { UserAgent: "*" },
            { Disallow: "/" },
        ],
    }]
],
```
or
```js
modules: [
    // ...
    "@nuxtjs/robots",
],
robots: {
    rules: [
        { UserAgent: "*" },
        { Disallow: "/" },
    ],
},
```
