### ISSUE TITLE
robots.txt parser should not be case-sensitive for keys

### ISSUE THREAD

**Issue by botic** [nuxt-modules/robots#146]
The current implementation is strict on the casing of keys inside a provided `robots.txt` with `mergeWithRobotsTxtPath`. This can have unexpected consequences, if you are using a perfectly fine pre-existing file. All three options in this example are valid and should be respected, but only the `User-agent:` group can be parsed by the current parser:

```
User-agent: works
Allow: /foo
allow: /ignored-path-1

User-Agent: ignored-1
allow: /ignored-path2

user-agent: ignored-2
allow: /ignored-path3
```

Google's reference implementation in C [ignores the capitalization of keys](https://github.com/google/robotstxt/blob/86d5836ba2d5a0b6b938ab49501be0e09d9c276c/robots.cc#L714C1-L720C2):

```cpp
bool ParsedRobotsKey::KeyIsUserAgent(absl::string_view key,
                                     bool* is_acceptable_typo) {
  *is_acceptable_typo =
      (kAllowFrequentTypos && (absl::StartsWithIgnoreCase(key, "useragent") ||
                               absl::StartsWithIgnoreCase(key, "user agent")));
  return (absl::StartsWithIgnoreCase(key, "user-agent") || *is_acceptable_typo);
}
```

This also follows the [RFC 9309](https://datatracker.ietf.org/doc/html/rfc9309#section-2.2), where the BNF states:

```
startgroupline = *WS "user-agent" *WS ":" *WS product-token EOL
```

It might be enough to just lower-case all keys during the parsing phase. I created a [potential pull request in my personal repo](https://github.com/nuxt-modules/robots/compare/main...botic:nuxt-robots:main). Depending on the discussion in this issue, I would submit this as a pull request.

**Comment by harlan-zw** [comment]
Thanks for the detailed issue and PR! The google implementation is a great reference.

I've merged your PR as it looked perfect.
