### ISSUE TITLE
Doesn't work with windows and Nuxt3

### ISSUE THREAD

**Issue by alexiokay** [nuxt-modules/robots#86]
[https://github.com/nuxt-community/robots-module/issues/64](url)

` ERROR  [worker reload] [worker init] Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
  at new NodeError (node:internal/errors:371:5)
  at defaultResolve (node:internal/modules/esm/resolve:1016:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
  at link (node:internal/modules/esm/module_job:75:36)`

**Comment by seangwright** [comment]
Same, here's my error:

```
 ERROR  (node:23052) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

√ Nitro built in 492 ms                                                                   nitro 15:17:22
i Vite client warmed up in 3593ms                                                               15:17:22

 ERROR  [worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default 
ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'

  at new NodeError (node:internal/errors:393:5)
  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1026:11)
  at defaultResolve (node:internal/modules/esm/resolve:1106:3)
  at nextResolve (node:internal/modules/esm/loader:163:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)                        15:17:16  
  at link (node:internal/modules/esm/module_job:75:36)
```

## ENV

Windows 10

```
> node -v
v18.12.1
```

`package.json`

```json
  "dependencies": {
    "highlight.js": "11.7.0",
    "vue-gtag-next": "1.14.0"
  },
  "devDependencies": {
    "autoprefixer": "10.4.13",
    "nuxt": "3.0.0",
    "postcss": "8.4.19",
    "prettier": "2.8.0",
    "tailwindcss": "3.2.4",
    "typescript": "4.9.3",
    "vue-tsc": "1.0.11"
  },
  "engines": {
    "node": ">= 18.12.1"
  }
```

**Comment by MuhammadM1998** [comment]
Same error on `nuxt dev`. `nuxt generate` works

```
 ERROR  [worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'e:'

  at new NodeError (node:internal/errors:393:5)  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:986:11)
  at defaultResolve (node:internal/modules/esm/resolve:1066:3)
  at nextResolve (node:internal/modules/esm/loader:161:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:831:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:413:18)
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
  at link (node:internal/modules/esm/module_job:76:36)
```

**Comment by MuhammadM1998** [comment]
Anyone got this to work?

**Comment by Slowhalfframe** [comment]
> Same error on `nuxt dev`. `nuxt generate` works
> 
> ```
>  ERROR  [worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'e:'
> 
>   at new NodeError (node:internal/errors:393:5)  at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:986:11)
>   at defaultResolve (node:internal/modules/esm/resolve:1066:3)
>   at nextResolve (node:internal/modules/esm/loader:161:28)
>   at ESMLoader.resolve (node:internal/modules/esm/loader:831:30)
>   at ESMLoader.getModuleJob (node:internal/modules/esm/loader:413:18)
>   at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
>   at link (node:internal/modules/esm/module_job:76:36)
> ```

Same mistake.

**Comment by Gumbraise** [comment]
Is anyone can help us ? 1 month since the issue started and 2 weeks since the last reply. Someone need to fix this bug

**Comment by Gumbraise** [comment]
Hey guys, I maybe solved the issue. Create a file named `robots.config.ts` on your Nuxt root. And add this is it:
```ts
export default [
    { UserAgent: '*' },
    { Disallow: '/' },
    { BlankLine: true },
    { Comment: 'Comment here' },

    { Sitemap: (req) => `https://${req.headers.host}/sitemap.xml` }
]
```
This solved the issue for me

**Comment by MuhammadM1998** [comment]
@Gumbraise What you done is a workaround. The issue is not in the robots module itself

**Comment by Createitv** [comment]
> Hey guys, I maybe solved the issue. Create a file named `robots.config.ts` on your Nuxt root. And add this is it:
> 
> ```ts
> export default [
>     { UserAgent: '*' },
>     { Disallow: '/' },
>     { BlankLine: true },
>     { Comment: 'Comment here' },
> 
>     { Sitemap: (req) => `https://${req.headers.host}/sitemap.xml` }
> ]
> ```
> 
> This solved the issue for me

Thanks! This also work for me

**Comment by kordoulakis** [comment]
Workaround worked for me in Nuxt 3 as well.

> Hey guys, I maybe solved the issue. Create a file named `robots.config.ts` on your Nuxt root. And add this is it:
> 
> ```ts
> export default [
>     { UserAgent: '*' },
>     { Disallow: '/' },
>     { BlankLine: true },
>     { Comment: 'Comment here' },
> 
>     { Sitemap: (req) => `https://${req.headers.host}/sitemap.xml` }
> ]
> ```
> 
> This solved the issue for me

**Comment by Xyrai** [comment]
Since this seems to be the current fix, make sure that the set values align with your `robots.txt` requirements before copy pasting the content.

> Hey guys, I maybe solved the issue. Create a file named `robots.config.ts` on your Nuxt root. And add this is it:
> 
> ```ts
> export default [
>     { UserAgent: '*' },
>     { Disallow: '/' },
>     { BlankLine: true },
>     { Comment: 'Comment here' },
> 
>     { Sitemap: (req) => `https://${req.headers.host}/sitemap.xml` }
> ]
> ```
> 
> This solved the issue for me
