### ISSUE TITLE
[Question] How to pass multiple options?

### ISSUE THREAD

**Issue by kwiat1990** [nuxt-modules/robots#97]
Hey, I have multiple options for different bots, which look like this:
```txt
 User-agent: Googlebot
    Disallow: /nogooglebot/

    User-agent: *
    Allow: /

    Sitemap: `${process.env.CMS_URL}/sitemap/index.xml`
```

I wonder how I could mirror this file with the robots plugin? I have tried using an array for the `rules` but it returns only the last entry:

```ts
// config
robots: {
    rules: [
      {
        UserAgent: "Googlebot",
        Disallow: "/nogooglebot/",
      },
      {
        UserAgent: "*",
        Allow: "/",
      },
      { 
        Sitemap: `${process.env.STRAPI_URL}/sitemap/index.xml`
      },
    ],
  },

// robots.txt page:
User-agent: *
Disallow: 
```

**Comment by abyshake-anand** [comment]
robots: [
    {
      UserAgent: 'Googlebot',
      Disallow: ['/nogooglebot/'],
    },
    {
      UserAgent: '*',
      Allow: '/',
    },
  ],

**Comment by abyshake-anand** [comment]
```
robots: [
    {
        UserAgent: 'Googlebot',
        Disallow: [
            '/nogooglebot/'
        ]
    },
    {
        UserAgent: '*',
        Allow: '/',
    },
]
```

**Comment by kwiat1990** [comment]
I have tried with the very same config but got the output you can see in my previous message. I’ve also restarted dev server and even change user agent in Chrome to googlebot but it didn’t make any difference at all.

**Comment by yauri-io** [comment]
Sorry for messing the PR history.
